#!/usr/bin/env python
import xslurm_shared
import socket,httplib
import argparse
s = xslurm_shared.TimeoutServerProxy(xslurm_shared.job_url, allow_none = True)

parser = argparse.ArgumentParser(description='Cancel XSlurm job')
parser.add_argument('job_id', nargs='*')
args = parser.parse_args()

if not args.job_id:
    job_ids = [line for line in sys.stdin]
else:
    job_ids = args.job_id

try:
    for job_id in job_ids: 
        s.cancel_job(job_id)
except (socket.error, httplib.HTTPException), serror:
    print 'Job canceling failed, could not connect to XSlurm manager on ' + url
