#!/usr/bin/env python
import subprocess, sys, getopt, time, shlex
from subprocess import Popen
import os,sys
import signal
import psutil
import shutil
import random
import threading
import xslurm_shared
import socket
import httplib
import numpy
import resource

resource.setrlimit(resource.RLIMIT_NPROC, (8192, 16000))

PING_INTERVAL = 10
PING_TIMEOUT = 600
REQUEST_TIMEOUT = 60

REGISTRATION_ATTEMPTS = 5
REGISTRATION_SLEEP = 30
REGISTRATION_SLEEP_RANDOM = 180

address = xslurm_shared.address
port = xslurm_shared.port

mem = psutil.virtual_memory().total / (1024.0 ** 2)
cpu = psutil.cpu_count()

opts, args = getopt.getopt(sys.argv[1:],"a:p:c:m:",["address=","port=","cpu=","mem="])
for o, a in opts:
    if o in ('-a', '--address'):
        address = a
    elif o in ('-p', '--port'):
        port = a
    elif o in ('-c', '--cpu'):
        cpu = a
    elif o in ('-', '--mem'):
        mem = a


myip = xslurm_shared.get_hostname()
myid = myip #for now

#self register
print ("[%s] Preparing to register on " % str(myip)) + str(address) + ":" + str(port)
s = xslurm_shared.TimeoutServerProxy('http://' + str(address) + ":" + str(port), timeout = REQUEST_TIMEOUT, allow_none = True)

myid = None
attempt = REGISTRATION_ATTEMPTS
while attempt > 0 :
    e_memtot = min(psutil.virtual_memory().total / (1024.0 ** 2), mem)
    e_ncpu = min(psutil.cpu_count(), cpu)
    try :
        myid = s.register(myip, e_ncpu, e_memtot)
    except (socket.error, httplib.HTTPException), serror :
        attempt -= 1
        sleep_time = random.randint(REGISTRATION_SLEEP, REGISTRATION_SLEEP + REGISTRATION_SLEEP_RANDOM)
        print '[-] Failed registration, %d attempts left, sleeping for %d seconds' % (attempt, sleep_time)
        time.sleep(sleep_time)
    if myid is not None :
        break


last_seen = time.time()

if myid == "DENIED":
    print "[%s] Cluster manager does not like me..." % myip
    sys.exit()
else:
    print ("[%s] Registered with controller, got id: " % myip) + myid
 
def handler(signum, frame) :
    print ("[%s] CATCH SYSTEM EXIT" % myid)
    sys.stdout.flush()
    mode = xslurm_shared.STOPPING

    terminate_jobs()
    print ("[%s] CATCH SYSTEM EXIT 2" % myid)
    sys.stdout.flush()
    time.sleep(5) #allow job monitor to report back the demise of the jobs
    sys.exit()

def terminate_jobs():
    status.lock.acquire()
    for process in status.running_processes.values():
        try:
            os.killpg(os.getpgid(process.pid), signal.SIGTERM)
        except OSError:
            pass
    status.lock.release()

    counter = 20
    while counter > 0 and len(status.running_processes) > 0:
        time.sleep(1)
        counter -= 1
        print counter


    #kill any remaining jobs
    status.lock.acquire()
    for process in status.running_processes.values():
        print "\t[%s] Killing remaining process" % myid
        try:
            os.killpg(os.getpgid(process.pid), signal.SIGKILL)
        except OSError:
            pass
    status.lock.release()

class status:
    lock = None
    current_cpu = e_ncpu
    current_mem = e_memtot
    running_processes = {}
    assigned_jobs = {}
    return_codes = {}


def job_monitor(jobid, process, ncpu, mem):
    retcode = None
    report_time = time.time()
    print('Job %s monitoring started' % str(jobid))
    while retcode is None:
        retcode = process.poll()
        cur_time = time.time()
        if (cur_time - report_time) > 600.0:
            print('Job %s still running' % str(jobid))
            report_time = cur_time
        time.sleep(1)

    print("Job %s done with rcode %s" % (str(jobid), str(retcode)))
    status.lock.acquire()
    status.return_codes[jobid] = retcode
    status.current_cpu += ncpu
    status.current_mem += mem
    del status.running_processes[jobid]

    event_timer.set()
    status.lock.release()
    print("Job %s monitoring stopped" % str(jobid))



status.lock = threading.RLock()


signal.signal(signal.SIGTERM, handler)

starttime = time.time()
last_seen = time.time()
mode = xslurm_shared.RUNNING
idle_start = 0
event_timer = threading.Event()

try :
    #lengine_monitor = psutil.Process(lengine.pid)

    while True:
        sys.stderr.flush()
        sys.stdout.flush()
        event_timer.clear()

        while status.return_codes:
            status.lock.acquire()
            nretcodes = {}
            for jobid, rcode in status.return_codes.items():
                try :
                    s.job_finished(myid, jobid, rcode)
                    print 'Reported that job %s finished with rcode %s' % (str(jobid), str(rcode))
                except (socket.error, httplib.HTTPException), serror :
                    print '[%s] Caught a socket error at time %f for jobid %s!' % (myid, time.time(), str(jobid))
                    nretcodes[jobid] = rcode
            status.return_codes = nretcodes
            status.lock.release()
       
       
        status.lock.acquire()   
        
        if mode == xslurm_shared.RUNNING and status.current_cpu > 0 and status.current_mem > 0 and psutil.virtual_memory().percent < 75.0:
            if status.assigned_jobs:
                jobs = status.assigned_jobs.values()
            else:
                try :
                    jobs = s.request_jobs(myid, status.current_cpu, status.current_mem)
                    print(jobs, status.current_cpu, status.current_mem)
                except (socket.error, httplib.HTTPException), serror :
                    jobs = []

            for job in jobs: 
                jobid, command, cwd, env, ncpu, mem, state = job
                if state == 'ASSIGNED':
                    if status.current_cpu > ncpu and status.current_mem > mem:
                        try :
                            permission = s.can_run_assigned_job(myid, jobid)
                        except (socket.error, httplib.HTTPException), serror :
                            continue
                        del status.assigned_jobs[jobid]
                        if not permission:
                            continue
                    else:
                        if not jobid in status.assigned_jobs:
                            status.assigned_jobs[jobid] = job
                        continue

                #start job
                curdir = os.getcwd()
                os.chdir(cwd)

                logfile = open('xslurm-%s.out' % jobid,'w')

                command = shlex.split(command)
                process = subprocess.Popen(command,stdout=logfile,stderr=logfile,cwd=cwd,env=env,preexec_fn=os.setpgrp)
                os.chdir(curdir)

                status.current_cpu -= ncpu
                status.current_mem -= mem
                status.running_processes[jobid] = process

                
                #start monitoring
                t = threading.Thread(target=job_monitor, args=(jobid, process, ncpu, mem))
                t.start()

        status.lock.release()

        if mode == xslurm_shared.STOPPING and not status.running_processes:
            break

           
        #POLL
        cpu_usage = float(numpy.mean(psutil.cpu_percent(percpu=True)))
        mem_usage = psutil.virtual_memory().percent
        idle = len(status.running_processes) == 0
        if idle and idle_start == 0:
            idle_start = time.time()
        elif not idle:
            idle_start = 0
        try:
            if idle_start == 0:
                commands = s.poll(myid, cpu_usage, mem_usage, mode, 0.0)
            else:
                commands = s.poll(myid, cpu_usage, mem_usage, mode, time.time() - idle_start)
            last_seen = time.time()
        except (socket.error, httplib.HTTPException), serror :
            print '[%s] Caught a socket error for command poll !' % myid
            if time.time() - last_seen > PING_TIMEOUT:
                print '[%s] Timeout triggered!' % myid
                mode=xslurm_shared.STOPPING

        for cmd, param in commands:
            if (cmd == xslurm_shared.STOP) :
                print '[%s] Received command to stop.' % myid
                mode = xslurm_shared.STOPPING
            elif (cmd == xslurm_shared.DIE):
                print '[%s] Received command to die.' % myid
                mode = xslurm_shared.STOPPING

                terminate_jobs()
            elif (cmd == xslurm_shared.DEASSIGN):
                print ('[%s] Received command to deassign job: ' % myid)+ str(param)
                status.lock.acquire()
                jobid = param
                if jobid in status.assigned_jobs:
                    del status.assigned_jobs[jobid]
                status.lock.release()
            elif (cmd == xslurm_shared.CANCEL):
                print ('[%s] Received command to cancel job: ' % myid)+ str(param)
                status.lock.acquire()
                jobid = param
                if jobid in status.running_processes:
                    
                    p = status.running_processes[jobid]
                    try:
                        os.killpg(os.getpgid(p.pid), signal.SIGTERM)
                    except OSError:
                        pass
                status.lock.release()
                
                time.sleep(5) #allow jobs some time to terminate normally

                #kill any remaining jobs
                status.lock.acquire()
                jobid = param
                if jobid in status.running_processes:
                    p = status.running_processes[jobid]
                    try:
                        os.killpg(os.getpgid(p.pid), signal.SIGKILL)
                    except OSError:
                        pass
                status.lock.release()
            elif (cmd == xslurm_shared.REREGISTER):
                print ('[%s] Received command to reregister.' % myid)
                try:
                    myid = s.register(myip, e_ncpu, e_memtot)
                except (socket.error, httplib.HTTPException), serror :
                    pass
                if myid == 'DENIED':
                    print ('[%s] Denied reregistration, stopping.' %myid)
                    mode = xslurm_shared.STOPPING

            else :
                print "[%s] UNKNOWN COMMAND RECEIVED, EXITING!" %myid
                break
        event_timer.wait(PING_INTERVAL)

    sys.stdout.flush()
    sys.stderr.flush()

    s.unregister(myid)


except (Exception, KeyboardInterrupt, SystemExit) :
    sys.stdout.flush()
    sys.stderr.flush()

    s.unregister(myid)
    raise
