#!/usr/bin/env python
import xslurm_shared
import getpass
import socket, httplib

s = xslurm_shared.TimeoutServerProxy(xslurm_shared.job_url, allow_none = True)

try:
    jobs = s.list_jobs()
    user = getpass.getuser()
    
    print "JOBID\tPARTITION\tNAME\tUSER\tST\tTIME\tCORES\tNODES"
    for jobid, job_name, state, run_time, cpus, node in jobs:
        days = 0
        hours = 0
        minutes = 0
        while runtime > (24 * 60 * 60):
            days += 1
            runtime -= 24 * 60 * 60
        while runtime > 60 * 60:
            hours += 1
            runtime -= 60 * 60
        while runtime > 60:
            minutes += 1
            runtime -= 60
        seconds = runtime
        runtime = '%d:%d:%d' % ( hours, minutes, seconds)
        if days > 0:
            runtime = ('%d-' % days) + runtime

        print '%s\tnormal\t%s\t%s\t%s\t%s\t%d\t%s' % (jobid, job_name, user, state, run_time, cpus, node)

except (socket.error, httplib.HTTPException), serror:
    print 'Queue request failed, could not connect to XSlurm manager on ' + url
